
//Таблица film_likes не пригодилась
drop table if exists users cascade;
drop table if exists user_friends cascade;
drop table if exists films cascade;
drop table if exists film_likes cascade;
drop table if exists genres cascade;
drop table if exists ratings cascade;
drop table if exists film_genres cascade;

create table IF NOT EXISTS users
(
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar,
    login    varchar,
    name     varchar,
    birthday date
);

create table IF NOT EXISTS user_friends
(
    user_id   int,
    friend_id int,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);

create table IF NOT EXISTS genres
(
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar
);

create table IF NOT EXISTS ratings
(
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating varchar
);

create table IF NOT EXISTS films
(
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar,
    description  varchar,
    release_date date,
    duration     integer,
    rating_id    integer,
    likes        integer,
    FOREIGN KEY (rating_id) REFERENCES ratings (id) ON DELETE CASCADE
);

create table IF NOT EXISTS film_likes
(
    film_id integer,
    user_id integer,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

create table IF NOT EXISTS film_genres
(
    film_id  integer,
    genre_id integer,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE
);


insert into genres (genre)
values ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');

insert into ratings (rating)
values ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');